spring.application.name=rate-limiter

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Rate Limiter Configuration
# Max requests allowed per client per window
rate.limiter.max-tokens=10
# Window duration in seconds
rate.limiter.window-seconds=60

server.port=8080
